version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gopickup-frontend.rule=Host(`main.gopickup.com.ng`)"
      - "traefik.http.services.gopickup-frontend.loadbalancer.server.port=80"
