# Simple Nginx container to serve the pre-built Flutter Web app
# Prerequisite: run 'flutter build web --release' locally
FROM nginx:alpine

# Copy the build output from the local build folder
COPY build/web /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf


# Expose port 80
EXPOSE 80

# Command to run nginx
CMD ["nginx", "-g", "daemon off;"]
